import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    gallerySidebar: [
        {
            type: 'category',
            label: 'Infrastruktur',
            link: {
                type: 'doc',
                id: 'infrastructure/index'
            },
            items: [
                {
                    type: 'link',
                    label: 'WLAN',
                    customProps: {
                        icon: 'mdiWifi'
                    },
                    href: 'https://ict-v1.gbsl.website/byod/wlan/'
                },
                {
                    type: 'link',
                    label: 'Drucker',
                    customProps: {
                        icon: 'mdiPrinter'
                    },
                    href: 'https://ict-v1.gbsl.website/infra/uniflow-drucker/'
                },
                {
                    type: 'link',
                    label: 'Unterrichtszimmer',
                    customProps: {
                        icon: 'mdiHomeCircle'
                    },
                    href: 'https://ict-v1.gbsl.website/infra/unterrichtszimmer/'
                },
                {
                    type: 'link',
                    label: 'OneDrive',
                    customProps: {
                        icon: 'mdi-microsoft-onedrive'
                    },
                    href: 'https://ict-v1.gbsl.website/byod/onedrive/'
                },
                {
                    type: 'link',
                    label: 'OneNote',
                    customProps: {
                        icon: 'mdiMicrosoftOnenote'
                    },
                    href: 'https://ict-v1.gbsl.website/byod/onenote/'
                },
                {
                    type: 'link',
                    label: 'Teams',
                    customProps: {
                        icon: 'mdi-microsoft-teams'
                    },
                    href: 'https://ict-v1.gbsl.website/byod/teams/'
                }
            ]
        },
        { type: 'autogenerated', dirName: '.' }
    ]

    // But you can create a sidebar manually
    /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
